---
name: build-iPXE
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: 35 01 * * *

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                binary: ['bin/undionly.kpxe', 'bin-x86_64-efi/ipxe.efi']
        steps:
            - name: Create todays tag
              run: printf '::set-env name=current-tag::%(%Y-%m-%d)T\n' '-1'
            - name: Install Build Dependencies
              run: >
                  sudo
                  apt-get install -y
                  binutils-dev
                  liblzma-dev
                  syslinux
                  genisoimage
                  jq
            - name: Get latest ipxe/ipxe tag json from API
              uses: JamesIves/fetch-api-data-action@1.0.15
              with:
                  ENDPOINT: https://api.github.com/repos/ipxe/ipxe/tags
                  SAVE_NAME: ipxe-ipxe-tags
            - name: Extract latest version tag from ipxe/ipxe json
              run: echo "::set-env name=ipxe-ipxe-tag::$(jq -r '.[0].name' fetch-api-data-action/ipxe-ipxe-tags.json)"
            - name: Get old ipxe/ipxe tag
              uses: actions/download-artifact@v2.0.5
              with:
                  name: old-ipxe-ipxe-tag
            - name: Checkout ${{ github.repository }}
              uses: actions/checkout@v2
            - name: Checkout ipxe/ipxe
              uses: actions/checkout@v2
              with:
                  repository: ipxe/ipxe
                  ref: ${{ env.ipxe-ipxe-tag }}
                  path: ipxe
            - name: Put custom config into the build dir
              run: >
                  cp
                  $GITHUB_WORKSPACE/general.h
                  $GITHUB_WORKSPACE/ipxe/src/config/local/
            - name: Build iPXE ${{ matrix.binary }}
              env:
                  BINARY: ${{ matrix.binary }}
              run: make -C src "$BINARY"
              working-directory: ipxe
            - name: Get filename from ${{ matrix.binary }}
              env:
                  BINARY: ${{ matrix.binary }}
              run: echo "::set-env name=filename::${BINARY##*/}"
            - name: Make release
              uses: eine/tip@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  files: ipxe/src/${{ matrix.binary }}
                  rm: True
                  snapshots: False
                  tag: ${{ env.current-tag }}
