# This is a basic workflow to help you get started with Actions

name: build-iPXE

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      name: Checkout ipxe/ipxe
      with:
        repository: ipxe/ipxe
        path: ipxe

    - uses: actions/checkout@v2
      name: Checkout ${{ github.repository }}
      with:
        path: custom-ipxe
    # Runs a single command using the runners shell
    - name: Put custom config into the build dri
      run: cp $GITHUB_WORKSPACE/custom-ipxe/general.h $GITHUB_WORKSPACE/ipxe/src/confg/local/

    # Runs a set of commands using the runners shell
    - name: Build iPXE EFI
      run: make bin-x86_64-efi/ipxe.efi
      working-directory: $GITHUB_WORKSPACE/ipxe/src
    - name: Upload ipxe.efi
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ipxe.efi
        path: $GITHUB_WORKSPACE/ipxe/src/bin-x86_64-efi/ipxe.efi
        if-no-files-found: error 
