---
name: build-iPXE
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-20.04

        steps:
            - name: Install Build Dependencies
              run: >
                  sudo
                  apt-get install -y
                  binutils-dev
                  liblzma-dev
                  syslinux
                  genisoimage
            - uses: actions/checkout@v2
              name: Checkout ${{ github.repository }}
            - uses: actions/checkout@v2
              name: Checkout ipxe/ipxe
              with:
                  repository: ipxe/ipxe
                  ref: v1.20.1
                  path: ipxe
            - name: Put custom config into the build dir
              run: >
                  cp
                  $GITHUB_WORKSPACE/general.h
                  $GITHUB_WORKSPACE/ipxe/src/config/local/
            - name: Show which version will be build
              run: make -C src version
              working-directory: ipxe
            - name: Build iPXE EFI
              run: make -C src bin-x86_64-efi/ipxe.efi
              working-directory: ipxe
            - name: Build iPXE undionly.kpxe
              run: make -C src bin/undionly.kpxe
              working-directory: ipxe
            - name: Upload ipxe.efi
              uses: actions/upload-artifact@v2.1.4
              with:
                  name: ipxe.efi
                  path: ipxe/src/bin-x86_64-efi/ipxe.efi
                  if-no-files-found: error
            - name: Upload undionly.kpxe
              uses: actions/upload-artifact@v2.1.4
              with:
                  name: undionly.kpxe
                  path: ipxe/src/bin/undionly.kpxe
                  if-no-files-found: error
